name: coffee_image

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    agentview_image:
      shape: [3, 84, 84]
      type: rgb
    robot0_eye_in_hand_image:
      shape: [3, 84, 84]
      type: rgb
    robot0_eef_pos:
      shape: [3]
      # type default: low_dim
    robot0_eef_quat:
      shape: [4]
    robot0_gripper_qpos:
      shape: [2]
  action: 
    shape: [7]
  flow:
    agentview_image:
      shape: [2, 84, 84]
      type: rgb

task_name: &task_name coffee_d0
dataset_type: &dataset_type mimicgen
dataset_path: &dataset_path
- "data/core/coffee_d0.hdf5"
# - "data/core/coffee_d1.hdf5"
# - "data/core/coffee_d2.hdf5"
main_dataset_path: &main_dataset_path data/core/coffee_d0.hdf5
abs_action: &abs_action False

env_runner:
  _target_: diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner
  dataset_path: *main_dataset_path
  shape_meta: *shape_meta
  # costs 1GB per env
  n_train: 0
  n_train_vis: 0
  train_start_idx: 0
  n_test: 1
  n_test_vis: 1
  test_start_seed: 100000
  # use python's eval function as resolver, single-quoted string as argument
  max_steps: ${eval:'500 if "${task.dataset_type}" == "mh" else 400'}
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  render_obs_key: 'agentview_image'
  fps: 10
  crf: 22
  past_action: ${past_action_visible}
  abs_action: *abs_action
  tqdm_interval_sec: 1.0
  n_envs: 1
# evaluation at this config requires a 16 core 64GB instance.

# dataset:
#   _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
#   shape_meta: *shape_meta
#   dataset_path: *dataset_path
#   horizon: ${horizon}
#   pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
#   pad_after: ${eval:'${n_action_steps}-1'}
#   n_obs_steps: ${dataset_obs_steps}
#   abs_action: *abs_action
#   rotation_rep: 'rotation_6d'
#   use_legacy_normalizer: False
#   use_cache: True
#   seed: 42
#   val_ratio: 0.02

# dataset:
#   _target_: diffusion_policy.dataset.robomimic_replay_action_dataset.RobomimicReplayActionDataset
#   shape_meta: *shape_meta
#   dataset_path: *dataset_path
#   horizon: ${horizon}
#   pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
#   pad_after: ${eval:'${n_action_steps}-1'}
#   abs_action: *abs_action
#   rotation_rep: 'rotation_6d'
#   seed: 42
#   val_ratio: 0.02

dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_image_flow_dataset.RobomimicReplayImageFlowDataset
  shape_meta: *shape_meta
  dataset_path: *dataset_path
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: *abs_action
  rotation_rep: 'rotation_6d'
  use_cache: True
  seed: 42
  val_ratio: 0.02
